project:
  type: website
  output-dir: ../docs
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!0_dataAssessment.ipynb"
    - "!5_postprocessing.ipynb"

website:
  title: "Sondondo Project Notebooks"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - text: Notebooks
        contents:
          - href: 1_dataCleaning.ipynb
            text: Data Cleaning
          - href: 2_placeMapping.ipynb
            text: Place Mapping
          - href: 3_termExtraction.ipynb
            text: Textual Variation Analysis for 'Conditions' Columns
          - href: 4_personasCreation.ipynb
            text: Personas Creation
      - text: Documentation
        contents:
          - href: docpages/schema_documentation.qmd
            text: Database Schema Documentation
format:
  html:
    theme: cosmo
    toc: true
