project:
  type: website
  output-dir: ../docs
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!x_*.ipynb"

website:
  title: "Sondondo Project Notebooks"
  page-footer:
    left: |
      **Sondondo Parish Records Project** v0.3.0  
      [UCSB Archives, Memory & Preservation Lab](https://ampl.clair.ucsb.edu/project/sondondo)
    center: |
      Licensed under [MIT License](https://github.com/UCSB-AMPLab/sondondo/blob/main/LICENSE)
    right: |
      Built with [Quarto](https://quarto.org/)  
      [<i class="bi bi-github"></i> Source](https://github.com/UCSB-AMPLab/sondondo)
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - text: Notebooks
        contents:
          - href: 1_dataCleaning.ipynb
            text: Data Cleaning
          - href: 2_placeMapping.ipynb
            text: Place Mapping
          - href: 3_termExtraction.ipynb
            text: Textual Variation Analysis for 'Conditions' Columns
          - href: 4_personasCreation.ipynb
            text: Personas Creation
          - href: 5_visualizations.ipynb
            text: Visualizations
      - text: Documentation
        contents:
          - href: docpages/metadata_dictionary.qmd
            text: Metadata Dictionary
format:
  html:
    theme: cosmo
    toc: true
